### ISSUE TITLE
Enhancement: Input subclasses refactoring

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/anta#388]
Tests Input subclasses should be moved outside of test classes, in other modules to allow reusability across tests and easier imports by external framework leveraging ANTA (AVD).

Solution:

Models are being moved to `anta.input_models.<module>`. Each test will keep a class variable as a reference of these models to avoid breaking changes. The references will be removed in ANTA v2.0.

Example:
```
from anta.input_models.connectivity import Host

class Input(AntaTest.Input):
    """Input model for the VerifyReachability test."""

    hosts: list[Host]
    """List of host to ping."""
    Host: ClassVar[type[Host]] = Host
```

- As part of this refactoring, `model_config = ConfigDict(extra="forbid")` should be added to these models to fix #809. 
- A `__str__`  should also be added to the models and be leveraged to improve failure messages, to fix #587.
- Need to add documentation for input models. Ref #912 

# Checklist (in priority):

High priority (AVD tests or high reusability):
- [x] VerifyReachability.Input.Host #912
- [x] VerifyInterfacesStatus.Input.InterfaceState #899
- [x] VerifyNTPAssociations.Input.NTPServer #902
- [x] VerifyLLDPNeighbors.Input.Neighbor #915 
- [x] VerifySpecificIPSecConn.Input.IPSecPeers & IPSecConn - https://github.com/aristanetworks/anta/pull/933
- [x] VerifyStunClient..Input.ClientAddress - https://github.com/aristanetworks/anta/pull/934
- [x] VerifyAVTSpecificPath.Input.AVTPaths  -  https://github.com/aristanetworks/anta/pull/939
- [x] VerifyDNSServers.Input.DnsServer https://github.com/aristanetworks/anta/pull/920

The following 3 BGP tests should use the same model to replace <VerifyBGP...>.Input.BgpAfi:
- [x] VerifyBGPPeerCount, VerifyBGPPeersHealth, VerifyBGPSpecificPeers #888

These BGP tests should use the same `BgpPeer` model:
- [x] VerifyBGPPeerMPCaps #914
- [x] VerifyBGPPeerASNCap #914
- [x] VerifyBGPPeerRouteRefreshCap #914
- [x] VerifyBGPPeerMD5Auth #914
- [x] VerifyBGPAdvCommunities #914
- [x] VerifyBGPTimers #914
- [x] VerifyBGPPeerDropStats #914
- [x] VerifyBGPPeerUpdateErrors #914
- [x] VerifyBgpRouteMaps #914
- [x] VerifyBGPPeerRouteLimit #914

The BFD tests should use the same `BFDPeer` model:
- [x] VerifyBFDSpecificPeers, VerifyBFDPeersIntervals, VerifyBFDPeersRegProtocols - https://github.com/aristanetworks/anta/pull/926

Low priority (low reusability):
- [x] VerifyLACPInterfacesStatus.Input.LACPInterface https://github.com/aristanetworks/anta/pull/947
- [x] VerifyErrdisableRecovery.Input.ErrDisableReason https://github.com/aristanetworks/anta/pull/955
- [x] VerifyAPISSLCertificate.Input.APISSLCertificate https://github.com/aristanetworks/anta/pull/957
- [x] VerifyIPv4ACL.Input.IPv4ACL & IPv4ACLEntry https://github.com/aristanetworks/anta/pull/957
- [x] VerifySpecificPath.Input.RouterPath https://github.com/aristanetworks/anta/pull/965
- [x] VerifyHardwareFlowTrackerStatus.Input.FlowTracker & RecordExport & Exporter https://github.com/aristanetworks/anta/pull/964
- [x] ISIS  @vitthalmagadum 
  - [x] VerifyISISNeighborCount.Input.InterfaceCount https://github.com/aristanetworks/anta/pull/963
  - [x] VerifyISISInterfaceMode.Input.InterfaceState https://github.com/aristanetworks/anta/pull/963
  - [x] VerifyISISSegmentRoutingAdjacencySegments.Input.IsisInstance & Segment https://github.com/aristanetworks/anta/pull/963
  - [x] VerifyISISSegmentRoutingDataplane.Input.IsisInstance https://github.com/aristanetworks/anta/pull/963
  - [ ] VerifyISISSegmentRoutingTunnels.Input.Entry & Vias: https://github.com/aristanetworks/anta/pull/1037

**Comment by carl-baillargeon** [comment]
Models are being be moved to `anta.input_models.<module>`. Each test will keep a class variable as a reference of these models to avoid breaking changes. The references will be removed in ANTA v2.0.

Example:
```
class Input(AntaTest.Input):
    """Input model for the VerifyReachability test."""

    hosts: list[Host]
    """List of host to ping."""
        Host: ClassVar[type[Host]] = Host
```
